name: GitHub Python Actions Demo 2

on:
  schedule:
    - cron: '*/30 * * * *'  # 30분마다 실행 (UTC 시간 기준)

jobs:
  run-python-script:
    runs-on: ubuntu-latest  # 최신 Ubuntu 환경에서 실행

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.14'  # 사용할 Python 버전 지정 (예: 3.8, 3.9 등)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 필요한 경우 requirements.txt 파일을 사용하여 패키지 설치

    - name: Run Python script
      run: |
        python test_acdtions2.py  # 실행할 Python 스크립트 파일 이름 지정

    - name: Commit and Push Changes2
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

        git add NEWS/Today_Invest.md
        git add NEWS/dataframe.md

        git commit -m 'Update downloaded file'
        git push

        # git fetch
        # git checkout origin/master -- CNAME
        # git pull NEWS/dataframe
